github: ['jrohitofficial']
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: 'jrohitofficial_'
custom: ['jrohit.com.np']
